name = "Dark"

[primary]
primary = "#6200ee"
on_primary = "#ffffff"
primary_container = "#3700b3"
on_primary_container = "#ffffff"

[secondary]
secondary = "#03dac6"
on_secondary = "#ffffff"
secondary_container = "#018786"
on_secondary_container = "#ffffff"

[tertiary]
tertiary = "#bb86fc"
on_tertiary = "#000000"
tertiary_container = "#6200ee"
on_tertiary_container = "#000000"

[error]
error = "#b00020"
on_error = "#ffffff"
error_container = "#cf6679"
on_error_container = "#000000"

[surface]
surface = "#121212"
on_surface = "#ffffff"
on_surface_variant = "#b0b0b0"

[surface.surface_container]
lowest = "#1e1e2e"
low = "#333333"
base = "#444444"
high = "#555555"
highest = "#666666"

[inverse]
inverse_surface = "#212121"
inverse_on_surface = "#ffffff"
inverse_primary = "#bb86fc"

[outline]
outline = "#737373"
outline_variant = "#aaaaaa"
