name = "Dark"

[primary]
primary = "#6200ee"
on_primary = "#ffffff"
primary_container = "#e1bee7"
on_primary_container = "#000000"

[secondary]
secondary = "#03dac6"
on_secondary = "#ffffff"
secondary_container = "#018786"
on_secondary_container = "#ffffff"

[tertiary]
tertiary = "#bb86fc"
on_tertiary = "#000000"
tertiary_container = "#6200ee"
on_tertiary_container = "#000000"

[error]
error = "#b00020"
on_error = "#ffffff"
error_container = "#cf6679"
on_error_container = "#000000"

[surface]
surface = "#ffffff"
on_surface = "#000000"
on_surface_variant = "#757575"

[surface.surface_container]
lowest = "#fafafa"
low = "#eeeeee"
base = "#dddddd"
high = "#cccccc"
highest = "#bbbbbb"

[inverse]
inverse_surface = "#121212"
inverse_on_surface = "#ffffff"
inverse_primary = "#bb86fc"

[outline]
outline = "#757575"
outline_variant = "#b0b0b0"
