name: Test
on: [push, pull_request]
jobs:
  all:
    runs-on: ubuntu-latest
    env:
      RUSTFLAGS: --deny warnings
    steps:
    - uses: hecrj/setup-rust-action@v2
    - uses: actions/checkout@master
    - name: Install dependencies
      run: |
        export DEBIAN_FRONTED=noninteractive
        sudo apt-get -qq update
        sudo apt-get install -y libxkbcommon-dev clang mold
    - uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: ${{ runner.os }}-ci-${{ hashFiles('**/Cargo.lock') }}
    - name: Run tests
      run: cargo test --verbose --workspace -- --ignored
